services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "10000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "10001:5432"
    environment:
      POSTGRES_DB: desafio_database
      POSTGRES_USER: desafio_user
      POSTGRES_PASSWORD: desafio_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
